### PR TITLE
Add maintainers page with release process

### PR DESCRIPTION
**Pull request by MartinBasti**
New page is for OSBS project maintaners how to do releases

Signed-off-by: Martin Bašti <mbasti@redhat.com>

### CODE REVIEW

**Comment by athos-ribeiro** [comment]
Can we merge the URL fix to fix the CI?

**Comment by MartinBasti** [comment]
https://github.com/containerbuildsystem/osbs-docs/pull/136

**Comment by tkdchen** [comment]
For Fedora, is Bodhi process required?

**Comment by MartinBasti** [comment]
> For Fedora, is Bodhi process required?

Yes, but I wouldn't cover distro specific steps here.

**Pull request closed without merging**
