### PR TITLE
Update reactor config map example with new registries_cfg_path config

### PR DESCRIPTION
**Pull request by tkdchen**
* CLOUDBLD-9346

Signed-off-by: Chenxiong Qi <cqi@redhat.com>

### CODE REVIEW

**Review by chmeliik — COMMENTED** [review]
Could we also explain what format the file should have (this one, I believe? https://www.mankier.com/5/containers-auth.json) and that it's the auth file for *all* push and pull registries?

**Comment by tkdchen** [comment]
The whole "Reactor Configuration" section looks incomplete. There is still confusion about the configuration file. For example,

* `Dockercfg` accepts both file names `.dockercfg` and `.dockerconfigjson`, and both of these two kinds of configuration accept two formats, one has `auths` key but another one doesn't. The comment tells "# If the auths key exist then we have a dockerconfigjson secret.", however, both the link you gave and an AWS doc I found tell the `auths` key works for `.dockercfg` as well.
* Is the configuration file used by a-r code only? How the different format affects the podman-remote by passing via the `--authfile`?

A few things are still not clear enough yet. I think it would be good to explain the relative part of reactor config in a dedicated story. And perhaps some "dead code" can also be removed, e.g. `unpack_auth_b64`.

**Comment by chmeliik** [comment]
+1 for dedicated story :+1:

**Review by chmeliik — APPROVED** [review]
LGTM :+1:

**Pull request merged**
